run:
  timeout: 5m
linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - golint
    - gocyclo
    - gosec
    - revive
    - ineffassign
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
