services:
  back:
    container_name: back
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET_KEY: ultra-secret-key
      DB_USER: ttavito
      DB_PASSWORD: ttavito
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ttavito
      PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ttavito
      POSTGRES_PASSWORD: ttavito
      POSTGRES_DB: ttavito
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ttavito -d ttavito" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres_data: